Like dbus just add the user:group to the filesystem package. EC is patent encumbered, do not generate the host key

diff --git a/core/openssh/openssh.install b/core/openssh/openssh.install
--- a/core/openssh/openssh.install
+++ b/core/openssh/openssh.install
@@ -1,15 +1,3 @@
-_addgroup() {
-  if ! bin/grep -q "^$1:" etc/group; then
-    usr/sbin/groupadd ${@} >/dev/null
-  fi
-}
-
-_adduser() {
-  if ! bin/grep -q "^$1:" etc/passwd; then
-    usr/sbin/useradd ${@} >/dev/null
-  fi
-}
-
 _gen_key() {
   local type=$1 key ks
   [ $# -eq 1 ] && ks="${type}_"
@@ -21,16 +9,6 @@ _gen_key() {
 }
 
 post_install() {
-  _addgroup sshd    -g 22
-  _adduser  sshd    -u 22 -d /var/empty -g sshd -s /sbin/nologin
-
-  _gen_key dsa >/dev/null 2>&1 || echo "gen_key failed!"
-  _gen_key rsa >/dev/null 2>&1 || echo "gen_key failed!"
-  _gen_key ecdsa >/dev/null 2>&1 || echo "gen_key failed!"
-
-  usr/sbin/grpconv >/dev/null
-
-  if LANG=C usr/bin/chage -l sshd | bin/grep -q 'password must be changed'; then
-    usr/bin/chage -d 14871 sshd
-  fi
+  _gen_key dsa >/dev/null 2>&1 || echo "gen_key dsa failed!"
+  _gen_key rsa >/dev/null 2>&1 || echo "gen_key rsa failed!"
 }
