upgrade to 2.22. No unexpected failures
Signed-off-by: Eduardo Tongson <ed@gimokod.org>

diff --git a/core/binutils/PKGBUILD b/core/binutils/PKGBUILD
--- a/core/binutils/PKGBUILD
+++ b/core/binutils/PKGBUILD
@@ -1,39 +1,43 @@
 # Based upon the PKGBUILD from Arch Linux. Debian and Gentoo's patches
 pkgname=binutils
-pkgver=2.21.1
+pkgver=2.22
 pkgrel=1
 pkgdesc="A set of programs to assemble and manipulate binary and object files"
-arch=('i686' 'x86_64')
+arch=('x86_64')
 url="http://www.gnu.org/software/binutils/"
 license=('GPL')
 groups=('base-devel')
 depends=('zlib')
+checkdepends=('dejagnu')
 install=binutils.install
 options=('!libtool' '!distcc' '!ccache')
 build() {
   cd ${srcdir}/${pkgname}-${pkgver}
-  # Gentoo
-  patch -Np0 -i ../08_all_binutils-RPATH_ENVVAR-smack.patch
-  patch -Np0 -i ../20_all_ld-sysroot.patch
-  patch -Np1 -i ../40_all_binutils-ld-gcc-4.6-tests.patch
 
   # Debian
-  patch -Np1 -i ../128_build_id.patch
-  patch -Np1 -i ../131_ld_bootstrap_testsuite.patch
+  Patch 001_ld_makefile_patch.patch
+  Patch 006_better_file_error.patch
+  Patch 012_check_ldrunpath_length.patch
+  Patch 013_bash_in_ld_testsuite.patch
+  Patch 128_build_id.patch
+  Patch 131_ld_bootstrap_testsuite.patch
+  Patch 157_ar_scripts_with_tilde.patch
+  Patch 167_pr13302.diff
+  Patch 168_readelf_go.patch
+  Patch pr13534-01.diff
+  Patch pr13534-02.diff
+  Patch pr13534-03.diff
+  Patch pr13534-04.diff
+  Patch pr13534-05.diff
 
-  patch -Np1 -i ../pr12654.patch
-  patch -Np1 -i ../pr12851a.patch
-  patch -Np0 -i ../pr12851b.patch
-  patch -Np1 -i ../pr12851c.patch
-  patch -Np1 -i ../pr12975.patch
-  patch -Np1 -i ../pr13195.patch
-  patch -Np1 -i ../pr13201.patch
-  patch -Np1 -i ../pr13233.patch
-  patch -Np1 -i ../binutils-2.21.1-claimfile-fix.patch
+  # Gentoo
+  Patch 08_all_binutils-RPATH_ENVVAR-smack.patch
+  Patch 20_all_ld-sysroot.patch
+
+  Patch pr13817.diff
 
   cd ${srcdir}
   mkdir binutils-build && cd binutils-build
-  [[ $CARCH == "x86_64" ]] && CONFIGFLAG="--enable-64-bit-bfd --disable-multilib"
   CFLAGS=${CFLAGS/-Os/-O2}
   CXXFLAGS=${CXXFLAGS/-Os/-O2}
   ${srcdir}/${pkgname}-${pkgver}/configure --prefix=/usr \
@@ -43,16 +47,34 @@ build() {
                                --enable-threads \
                                --enable-shared \
                                --without-included-gettext \
-                               --disable-nls $CONFIGFLAG
-
+                               --disable-nls \
+                               --enable-64-bit-bfd \
+                               --disable-multilib
+  echo "MAKEINFO = :" >> Makefile
   make configure-host
   make tooldir="${pkgdir}"/usr
+
+  # Rebuild libiberty.a with -fPIC
+  cp -a libiberty libiberty-pic
+  make -C libiberty-pic clean
+  make CFLAGS="$CFLAGS -fPIC" -C libiberty-pic
+
+  # Rebuild libbfd.a with -fPIC
+  # hidden visability prevent 3rd party shared libraries exporting bfd non-stable API
+  cp -a bfd bfd-pic
+  make -C bfd-pic clean
+  make CFLAGS="$CFLAGS -fPIC -fvisibility=hidden" -C bfd-pic
+
+  # Rebuild libopcodes.a with -fPIC
+  cp -a opcodes opcodes-pic
+  make -C opcodes-pic clean
+  make CFLAGS="$CFLAGS -fPIC" -C opcodes-pic
 }
 
 check() {
   cd "${srcdir}"/binutils-build
-  # do not abort on errors - manually check log files
-   make -k -j1 check || true
+  make -k -j1 check || true
+  # FAIL -> RUNTESTFLAGS=-v
 }
 
 package() {
@@ -60,61 +82,62 @@ package() {
   make prefix="${pkgdir}"/usr tooldir="${pkgdir}"/usr install
 
   # Add some useful headers
-  install -m644 "${srcdir}"/${pkgname}-${pkgver}/include/libiberty.h "${pkgdir}"/usr/include
-  install -m644 "${srcdir}"/${pkgname}-${pkgver}/include/demangle.h "${pkgdir}"/usr/include
+  install -m644 ${srcdir}/binutils-${pkgver}/include/libiberty.h ${pkgdir}/usr/include
+  install -m644 ${srcdir}/binutils-${pkgver}/include/demangle.h ${pkgdir}/usr/include
 
-  # Rebuild libiberty.a with -fPIC
-  make -C libiberty clean
-  make CFLAGS="$CFLAGS -fPIC" -C libiberty
-  install -m644 libiberty/libiberty.a "${pkgdir}"/usr/lib
-
-  # Rebuild libbfd.a with -fPIC
-  make -C bfd clean
-  # hidden visability prevent 3rd party shared libraries exporting bfd non-stable API
-  make CFLAGS="$CFLAGS -fPIC -fvisibility=hidden" -C bfd
-  install -m644 bfd/libbfd.a "${pkgdir}"/usr/lib
+  # install libraries rebuilt with -fPIC
+  install -m644 libiberty-pic/libiberty.a ${pkgdir}/usr/lib
+  install -m644 bfd-pic/libbfd.a ${pkgdir}/usr/lib
+  install -m644 opcodes/libopcodes.a ${pkgdir}/usr/lib
 
   # Remove Windows/Novell specific man pages
-  rm -f "${pkgdir}"/usr/share/man/man1/{dlltool,nlmconv,windres,windmc}*
+  rm -f ${pkgdir}/usr/share/man/man1/{dlltool,nlmconv,windres,windmc}*
 
   # Remove these symlinks, they are not ABI stable.
   # Programs should compile static to the .a file.
-  rm -f "${pkgdir}"/usr/lib/lib{bfd,opcodes}.so
-  echo "INPUT ( /usr/lib/libbfd.a -liberty -lz )" >"${pkgdir}"/usr/lib/libbfd.so
-  echo "INPUT ( /usr/lib/libopcodes.a -lbfd )" >"${pkgdir}"/usr/lib/libopcodes.so
+  rm -f ${pkgdir}/usr/lib/lib{bfd,opcodes}.so
+  echo "INPUT ( /usr/lib/libbfd.a -liberty -lz )" >${pkgdir}/usr/lib/libbfd.so
+  echo "INPUT ( /usr/lib/libopcodes.a -lbfd )" >${pkgdir}/usr/lib/libopcodes.so
+
   mv "${pkgdir}/usr/bin/strings" "${pkgdir}/usr/bin/gstrings"
 }
-source=(ftp://gcc.gnu.org/pub/binutils/snapshots/$pkgname-$pkgver.tar.bz2)
-sha256sums=('cdecfa69f02aa7b05fbcdf678e33137151f361313b2f3e48aba925f64eabf654')
+source=(http://ftp.gnu.org/gnu/binutils/$pkgname-$pkgver.tar.bz2)
+sha256sums=('6c7af8ed1c8cf9b4b9d6e6fe09a3e1d3d479fe63984ba8b9b26bf356b6313ca9')
 
 source=(${source[@]-}
+        001_ld_makefile_patch.patch
+        006_better_file_error.patch
+        012_check_ldrunpath_length.patch
+        013_bash_in_ld_testsuite.patch
         08_all_binutils-RPATH_ENVVAR-smack.patch
         128_build_id.patch
         131_ld_bootstrap_testsuite.patch
+        157_ar_scripts_with_tilde.patch
+        167_pr13302.diff
+        168_readelf_go.patch
         20_all_ld-sysroot.patch
-        40_all_binutils-ld-gcc-4.6-tests.patch
-        binutils-2.21.1-claimfile-fix.patch
-        pr12654.patch
-        pr12851a.patch
-        pr12851b.patch
-        pr12851c.patch
-        pr12975.patch
-        pr13195.patch
-        pr13201.patch
-        pr13233.patch)
+        pr13534-01.diff
+        pr13534-02.diff
+        pr13534-03.diff
+        pr13534-04.diff
+        pr13534-05.diff
+        pr13817.diff)
 
 sha256sums=(${sha256sums[@]-}
+            'abb214d3e337e79e6009693ed12b2d5f3f8ce9e89706d158a78de1f2aabad79e'
+            '9d874988e80a6941bc607722be9366a30fc7d55dbd2d2aada5354faa6dc37c74'
+            'c600d0deebdfe4b5e6e94489c035c802caa7b84aeed238f0c0d90882ae8fff56'
+            '75c4df149b23d7980c70c220b3f70cc01aa65e59c4e7eba91c9400fb27094ba7'
             'e6ad9a2161a635fdcbeff180b5e36c76d283be80e9b8de7ae3c1e79335ba3680'
             '308ed294365f59077d53a3cd0d95a6df2f71ec4bdd87a659478ec071e16726cb'
             '854856477128b2bc3ae70db123aaa0e9cb5072d5f3ed26cf8014c40a2688310c'
+            'f4b57b9ebd3c46580e227db17d6cb27b3a250de2a46f362c93e736d3162d3729'
+            '17fdb22f62eae42ee754873101d401bba465613962917a50f027ec92ffef41bc'
+            'b7344bbd896a2868e6f814bf30b37c373b4ea785b3847f1d04a50a7fec5a60ab'
             'b85eab89949d47314e10795256938198ae114b8c9a65cba18488790a2b3298a1'
-            '55688e1aa077ca81d687859c3e0b3306c8495a1cdcf57138c25669ab766dc2fc'
-            'e76c3e6df52edf5cd97f518d115d84b01525a8a0f40c826622b9ef086b06ea49'
-            '59ae2528b805b94c26f06484e5059060ce7f5c26b2b88696af808dfa99421d60'
-            '4565570ee901a60a547af445f85c88d631d6c54e20517a463ff5b1d6e338989f'
-            '22c9ffe4af24f9863e599479a47549505ab2eea757c30ab72c6554bdfc3bfe77'
-            '0ac9f4dd5888f3ba8d4b658ba11e9709691b4c571aa81ab438ac42b247296f82'
-            'a4c67e646742d1f6068faa91ad36fb136e9271bffff365aa41646b4152a1f6ad'
-            '5127df32122f849ad9957acc42627cb8c4472b152d00deaba67a1c65e462fe64'
-            'ca9aba8c1804254a45f470cde24930964c6bc34dcb1af6a45bad6baa97d07080'
-            '4de3477ccba1d31509446ac1ad1bf440aae1d185f11175b181f34e82d3a6028e')
+            '65a22a1e940ae39744729fa0a5fa4ec98ec20e2f723f261df6748656bd8ce8c1'
+            'fc7e6daf35509b7b56da889878a938d73558fe3f6a76ce37882bc9892c8fbc6c'
+            '7db9b9a4f5dbe66f76a94cdb91288a0a673b2478088120b125ab96a7b85302e9'
+            'a1e665ad3db7583f620ee7ea8b221c87ef0176c3489c69676979d8b3dd88a545'
+            '457d641ccd77da96706b8437205058d2f6313f4530a0aad04c493bfa4ab41865'
+            '87fecd1b3e558e1b45d0759a20154ac43385b4c2e5dfe02522ecf1d9b7608d9d')
